=== Lotoz/LLMM/Examenes/EXAMEN-DTD/ejercicio3.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellidos, domicilio, 
                    telefonos,equiposDeportivos?,aficiones,comentarios,evaluaciones)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefonos (telefono+)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT aficiones (aficion+)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT equiposDeportivos (#PCDATA)>
<!ELEMENT  comentarios (comentario*)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT evaluaciones (notas*)>
<!ELEMENT notas (#PCDATA)>
<!ATTLIST alumno num_alumno ID #REQUIRED
                 altura CDATA #IMPLIED
                 sexo CDATA #IMPLIED>
<!ATTLIST telefono pertenece (Propio|Padre|Madre|Tutor) #REQUIRED>
<!ATTLIST notas evaluacion (Primera|Segunda|Tercera) "Primera">

=== Lotoz/LLMM/Examenes/EXAMEN-DTD/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM 'ejercicio3.dtd'>
<alumnos>
    <alumno num_alumno="A1" altura="175cm" sexo="Hombre">
        <nombre>Jorge</nombre>
        <apellidos>Linus</apellidos>
        <domicilio>Calle 3</domicilio>
        <telefonos>
            <telefono pertenece="Propio">2167451</telefono>
            <telefono pertenece="Padre">24562345</telefono>
        </telefonos>
        <equiposDeportivos>La mancha</equiposDeportivos>
        <aficiones>
            <aficion>Escribir</aficion>
        </aficiones>
        <comentarios>
            <comentario>Buen alumno, callado, participa poco en clase</comentario>
            <comentario>Ha bajado la nota</comentario>
        </comentarios>
        <evaluaciones>
            <notas evaluacion="Primera">7</notas>
            <notas evaluacion="Segunda">6</notas>
        </evaluaciones>
    </alumno>
    <alumno num_alumno="A2">
        <nombre>Indigo</nombre>
        <apellidos>Ackerman</apellidos>
        <domicilio>Avenida de la macha</domicilio>
        <telefonos>
            <telefono pertenece="Tutor">32323423</telefono>
            <telefono pertenece="Madre">23213423</telefono>
        </telefonos>
        <aficiones>
            <aficion>Dibujar</aficion>
            <aficion>Leer</aficion>
        </aficiones>
        <comentarios></comentarios>
        <evaluaciones></evaluaciones>
    </alumno>
</alumnos>
